import { COMING_SOON_CONSENT_GATE_SNIPPET } from "@/lib/privacy-consent";

/**
 * Immediate Coming Soon guest ping — runs as a classic script before React hydrates.
 * Gated by optional analytics consent (`mks_consent.analytics === true`).
 */
export function ComingSoonGuestBeacon() {
  return (
    <script
      dangerouslySetInnerHTML={{
        __html: `(function(){try{${COMING_SOON_CONSENT_GATE_SNIPPET};if(!__mesaAnalyticsOk())return;window.__mesaGuestDocumentPv=1;function conn(){try{var ck=sessionStorage.getItem("mesa-guest-connection")||"";if(!ck||ck.length>80||!/^[A-Za-z0-9_-]+$/.test(ck)){ck=(crypto.randomUUID&&crypto.randomUUID().replace(/-/g,""))||("c"+Date.now()+"_"+Math.random().toString(36).slice(2));sessionStorage.setItem("mesa-guest-connection",ck)}return ck}catch(e){return""}}function readVisitor(){try{var k=localStorage.getItem("mesa-guest-visitor")||"";if(k&&k.length<=80&&/^[A-Za-z0-9_-]+$/.test(k))return k;return""}catch(e){return""}}function mintVisitor(){try{var k=(crypto.randomUUID&&crypto.randomUUID())||("v"+Date.now()+"_"+Math.random().toString(36).slice(2));localStorage.setItem("mesa-guest-visitor",k);return localStorage.getItem("mesa-guest-visitor")||k}catch(e){return (crypto.randomUUID&&crypto.randomUUID())||("v"+Date.now()+"_"+Math.random().toString(36).slice(2))}}function visitor(){return readVisitor()||mintVisitor()}function rotate(stale){try{var cur=readVisitor();if(cur&&cur!==stale)return cur;return mintVisitor()}catch(e){return mintVisitor()}}function rotateLocked(stale,cb){var run=function(){cb(rotate(stale))};if(navigator.locks&&navigator.locks.request){navigator.locks.request("mesa-guest-visitor-key",run).catch(run)}else{run()}}function utmPayload(){try{var p=new URLSearchParams(location.search||"");function clean(v,lower){if(v==null)return"";v=String(v).replace(/[\\u0000-\\u001F\\u007F]/g,"").trim();if(!v)return"";if(lower)v=v.toLowerCase();if(v.length>100)v=v.slice(0,100).trim();return v}var o={};var s=clean(p.get("utm_source"),!0);var m=clean(p.get("utm_medium"),!0);var c=clean(p.get("utm_campaign"),!1);if(s)o.utmSource=s;if(m)o.utmMedium=m;if(c)o.utmCampaign=c;return o}catch(e){return{}}}function send(vk,isRetry){var id=(crypto.randomUUID&&crypto.randomUUID())||("n"+Date.now()+"_"+Math.random().toString(36).slice(2));var body=Object.assign({path:location.pathname||"/",pageview:!0,navId:id,referer:document.referrer||"",connectionKey:conn(),clientVisitorKey:vk},utmPayload());fetch("/api/analytics/guest",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(body)}).then(function(r){if(r.status===409&&!isRetry){return r.json().catch(function(){return{}}).then(function(d){if(d&&(d.rotate||d.code==="stale_visitor")){rotateLocked(vk,function(fresh){try{localStorage.setItem("mesa-guest-visitor",fresh);localStorage.setItem("mesa-guest-rotated-at",String(Date.now())+":"+fresh)}catch(e){}send(fresh,!0)})}return null})}return r.json().catch(function(){return{}})}).then(function(d){if(d&&d.visitorKey){try{localStorage.setItem("mesa-guest-visitor",d.visitorKey)}catch(e){}}}).catch(function(){})}var run=function(){send(visitor(),!1)};if(navigator.locks&&navigator.locks.request){navigator.locks.request("mesa-guest-visitor-key",run).catch(run)}else{run()}}catch(e){}})();`,
      }}
    />
  );
}
